#include <stdio.h>
#include <unistd.h> 
#include <sys/wait.h>
int main(void)
{
		int pid; 

		pid = fork(); /* Spawn a new process */
		if(pid == 0) { // child
				printf("This is a Child generated by the first fork, pid=%d\n",getpid()); 
		} else if(pid == -1) { // uh oh...
				printf("fork() failed\n");
		} else { // parent
		        
				printf("This is the Parent, child id=%d, parent id=%d\n", pid, getpid());
				wait(NULL);
		}
}
