#include <stdio.h>
#include <unistd.h> 
#include <sys/wait.h>
int main(void)
{
		int pid; 

		pid = fork(); /* Spawn a new process */
		if(pid == 0) { // child
				printf("This is a Child generated by the first fork \n"); 
		} else if(pid == -1) { // uh oh...
				printf("fork() failed\n");
		} else { // parent
		        
				printf("This is the Parent\n");
				wait(NULL);
		}
}
