//****************************
// Hongzhi Guo
// Redesigned this example for 
// fork() demo
// 2/5/2023
//****************************
#include <stdio.h>
#include <unistd.h> 

int main(void)
{

		int pid; 

		pid = fork(); /* Spawn a new process */
		if(pid == 0)
				printf("This is a Child generated by the first fork, pid = %d, process id = %d\n", pid, getpid()); 
		pid = fork();
        if(pid == 0)
				printf("This is a Child generated by the second fork, pid = %d, process id = %d\n", pid, getpid());
}
